### ISSUE TITLE
KeyError: 'DuckKnows'

### ISSUE THREAD

**Issue by JarbasAl** [HelloChatterbox/ask-the-duck#1]
```
13:42:34.809 | ERROR | 629 | mycroft.skills.mycroft_skill.mycroft_skill:on_error:933 | An error occurred while processing a request in Duck Duck Go Skill
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper
handler(message)
File "/home/mycroft/.local/share/mycroft/skills/skill-ddg.jarbasskills/init.py", line 116, in handle_tell_more
query = message.data["DuckKnows"]
KeyError: 'DuckKnows'
```

**Comment by JarbasAl** [comment]
ups, wrong repo
